import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar"; // Import the Sidebar component
import { WagmiConnectionProvider } from "@/data/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multisig Wallet System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConnectionProvider>
          <div className="flex h-screen">
            <Sidebar />
            <div className="relative flex-1 overflow-hidden h-full w-ful">
              {children} {/* Page content */}
            </div>
          </div>
        </WagmiConnectionProvider>
      </body>
    </html>
  );
}
